POST http://localhost:27017/api/cars
Content-Type: application/json

{
  "make" : "acura",
  "model" : "tsx",
  "price" : 15000
}

###

GET http://localhost:27017/api/cars/66ecc6171cee9d7438fc40d9
Content-Type: application/json
